version: "3"
services:
  reverse-proxy:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/nginx.conf
    container_name: reverse_proxy
    ports:
      - 80:80
    networks:
      - shared-network

  react-app:
    image: react-app
    container_name: react-app
    build: 
      context: client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - shared-network
    volumes:
      - ./client/:/app
      - /app/node_modules
    depends_on:
      - api-server

  api-server:
    image: api-server
    container_name: api-server
    env_file: ./config.env
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    networks:
      - shared-network
    volumes:
      - ./:/app
      - /app/node_modules
      
networks:
  shared-network:

