version: "3"
services:
  reverse-proxy:
    image: nginx
    container_name: reverse_proxy
    depends_on:
        - react-app
        - api-server
    volumes:
      - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  react-app:
    image: react-app
    container_name: react-app
    build: ./client/
    ports:
      - "3000:3000"
    networks:
      - mern-app
    volumes:
      - ./client/:/app
      - /app/node_modules

  api-server:
    image: api-server
    container_name: api-server
    env_file: ./config.env
    build: ./
    ports:
      - "8000:8000"
    networks:
      - mern-app
    volumes:
      - ./:/app
      - /app/node_modules

